#!/usr/bin/env bash
# DGC SMS - Ubuntu Server Deployment Script
# Run as root or with sudo: sudo bash deploy.sh

set -e

APP_NAME="dgc_sms"
APP_DIR="/opt/dgc_sms"
APP_USER="dgc_sms"
VENV_DIR="$APP_DIR/venv"
DOMAIN="${1:-_}"  # Pass domain as argument, or default to any

echo "=== DGC SMS Deployment ==="

# 1. System packages
echo "[1/8] Installing system packages..."
apt update
apt install -y python3 python3-venv python3-pip nginx git openssl libreoffice-writer

# 2. Create app user
echo "[2/8] Creating application user..."
if ! id "$APP_USER" &>/dev/null; then
    useradd --system --shell /bin/false --home "$APP_DIR" "$APP_USER"
fi

# 3. Set up application directory
echo "[3/8] Setting up application directory..."
mkdir -p "$APP_DIR"
cp -r . "$APP_DIR/"
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip
"$VENV_DIR/bin/pip" install -r "$APP_DIR/requirements.txt"

# 4. Create .env file if not exists
if [ ! -f "$APP_DIR/.env" ]; then
    echo "[4/8] Creating .env configuration..."
    SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    cat > "$APP_DIR/.env" <<EOF
SECRET_KEY=$SECRET
FLASK_CONFIG=production
DATABASE_URL=sqlite:///$APP_DIR/instance/dgc_sms.db

# Site is served over HTTPS via the self-signed certificate generated by this script
SESSION_COOKIE_SECURE=true

# Email - Gmail SMTP settings for DGC
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=true
MAIL_USERNAME=dgcjamaica@gmail.com
MAIL_PASSWORD=your-app-password
MAIL_DEFAULT_SENDER=dgcjamaica@gmail.com
EOF
    echo "  >> Edit $APP_DIR/.env with your actual mail settings"
else
    echo "[4/8] .env already exists, skipping..."
fi

# 5. Initialize database
echo "[5/8] Initializing database..."
mkdir -p "$APP_DIR/instance" "$APP_DIR/uploads"
cd "$APP_DIR"
"$VENV_DIR/bin/python" -c "
import logging
# python-dotenv 1.0.x emits 'could not parse statement' messages via
# logger.warning() in dotenv.main — NOT via the warnings module.
# Raise the dotenv logger threshold to ERROR so these non-fatal parse
# notices are silenced while genuine errors (encoding failures, etc.)
# remain visible.
logging.getLogger('dotenv.main').setLevel(logging.ERROR)
from dotenv import load_dotenv
load_dotenv()
from app import create_app, db
app = create_app('production')
with app.app_context():
    db.create_all()
    print('  >> Database tables created')
"
"$VENV_DIR/bin/python" seed.py

# 6. Set permissions
echo "[6/8] Setting file permissions..."
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
chmod 600 "$APP_DIR/.env"

# 7. Generate self-signed TLS certificate
# Works with bare IP addresses and .local domains — no internet access required.
echo "[7/8] Generating self-signed TLS certificate..."
CERT_DIR="/etc/ssl/dgc_sms"
mkdir -p "$CERT_DIR"

# Build the SubjectAltName value: use IP: for bare IP addresses, DNS: for hostnames.
# The regex validates each octet is in the 0-255 range.
if [[ "$DOMAIN" =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
    SAN="IP:$DOMAIN"
else
    SAN="DNS:$DOMAIN"
fi

openssl req -x509 -nodes -days 3650 \
    -newkey ec -pkeyopt ec_paramgen_curve:P-384 \
    -keyout "$CERT_DIR/dgc_sms.key" \
    -out    "$CERT_DIR/dgc_sms.crt" \
    -subj   "/CN=$DOMAIN/O=DGC SMS/C=JM" \
    -addext "subjectAltName=$SAN"

chmod 600 "$CERT_DIR/dgc_sms.key"
echo "  >> Certificate valid for 10 years stored in $CERT_DIR"
echo "  >> Import $CERT_DIR/dgc_sms.crt into your browser/OS trust store to remove the warning"

# 8. Install systemd service + nginx
echo "[8/8] Installing systemd service and nginx config..."
cp "$APP_DIR/deployment/dgc_sms.service" /etc/systemd/system/dgc_sms.service

# Generate nginx config with the provided domain
sed "s/YOUR_DOMAIN_OR_IP/$DOMAIN/g" \
    "$APP_DIR/deployment/nginx_dgc_sms.conf" > /etc/nginx/sites-available/dgc_sms

ln -sf /etc/nginx/sites-available/dgc_sms /etc/nginx/sites-enabled/dgc_sms
rm -f /etc/nginx/sites-enabled/default

# Start services
systemctl daemon-reload
systemctl enable dgc_sms
# Use restart so re-runs pick up updated code/config; start if not yet running.
systemctl restart dgc_sms 2>/dev/null || systemctl start dgc_sms

# Validate nginx config, then do a clean stop → start cycle.
# Using stop+start (rather than restart) guarantees the old process is fully
# gone before we attempt to bind port 8080, which prevents "address already
# in use" failures when re-running the script or when a previous nginx.service
# attempt left the unit in a failed state.
nginx -t || { echo "ERROR: nginx configuration test failed — check the config above."; exit 1; }
systemctl stop nginx 2>/dev/null || true
systemctl reset-failed nginx 2>/dev/null || true
systemctl start nginx || {
    echo ""
    echo "ERROR: nginx failed to start. Diagnostics:"
    journalctl -u nginx --no-pager -n 30 2>/dev/null || true
    echo ""
    echo "Common causes:"
    echo "  1. Another process is already using port 8080."
    echo '     Check with: ss -tlnp | grep '"'"':8080'"'"
    echo "  2. The TLS certificate files at $CERT_DIR are unreadable."
    echo "     Check with: ls -la $CERT_DIR"
    echo "  3. An nginx module required by the config is not installed."
    echo "     Check with: journalctl -xeu nginx.service"
    exit 1
}

# Open port 8080 in the firewall if ufw is active
if command -v ufw &>/dev/null && ufw status | grep -q "^Status: active"; then
    echo "  >> Opening port 8080/tcp in ufw..."
    ufw allow 8080/tcp
fi

echo ""
echo "=== Deployment Complete ==="
echo "App running at: https://$DOMAIN:8080"
echo ""
echo "NOTE: Your browser will show a security warning because the certificate is"
echo "      self-signed. To silence it, import the certificate into your browser"
echo "      or OS trust store:"
echo "      $CERT_DIR/dgc_sms.crt"
echo ""
echo "Useful commands:"
echo "  sudo systemctl status dgc_sms    # Check app status"
echo "  sudo journalctl -u dgc_sms -f    # View app logs"
echo "  sudo systemctl restart dgc_sms   # Restart app"
echo "  sudo nano $APP_DIR/.env          # Edit configuration"
